-- Triggers
CREATE TABLE lab_audits ( 
      audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
      table_name       VARCHAR2(255), 
      transaction_name VARCHAR2(10), 
      by_user          VARCHAR2(30), 
      transaction_date DATE 
);

SELECT TRIGGER_NAME, TABLE_NAME, TRIGGER_TYPE, TRIGGERING_EVENT
FROM USER_TRIGGERS;

CREATE OR REPLACE TRIGGER customer_audit_trg 
    AFTER  
    INSERT OR UPDATE OR DELETE  
    ON lab_customer
    FOR EACH ROW     
DECLARE 
   l_transaction VARCHAR2(10); 
BEGIN 
   -- determine the transaction type 
   l_transaction := CASE  
         WHEN INSERTING THEN 'INSERT' 
         WHEN UPDATING THEN 'UPDATE' 
         WHEN DELETING THEN 'DELETE' 
   END; 
   INSERT INTO lab_audits (table_name, transaction_name, 
   by_user, transaction_date) 
   VALUES('lab_customer', l_transaction, USER, SYSDATE); 
END; 
/

INSERT INTO lab_customer VALUES (8,'hari','sharma','9841000007','AUS','hari@gmail.co');

update lab_customer 
set email='hari@gmail.com'
where customer_id=8;
select * from lab_audits;