# for project documents, use addtional latex styles used in final-report file
:edit-this:
#+EXPORT_FILE_NAME: java-lab6-report
#+PROPERTY: header-args :eval no-export
# don't prompt to evaluate code blocks while exporting
#+OPTIONS: toc:nil ^:{}
# set toc below instead of here
# 2nd option exports subscripts only when _{} is used
#+LATEX_HEADER: \graphicspath{{~/programming/college-files/assets/images/}}

# !!!!!!!!!!!!!          only edit this section       !!!!!!
#+LATEX_HEADER: \def\subjectNum{2}
# 1: ECON
# 2: JAVA
# 3: MOBILE
# 4: NETWORK
# 5: none

#+LATEX_HEADER: \def\labNum{6}
#+LATEX_HEADER: \def\labTitle{Servlets and JSP}
#+LATEX_HEADER: \def\yearSem{III/II}
#+LATEX_HEADER: \newif \iftoc
# !!!!!!!!!!!!           set toc here by uncommenting option
# \toctrue    
\tocfalse
:end:

#+INCLUDE: "~/programming/college-files/assets/template.org" :lines "27-"
* Objectives
- implement server side code with servlets
- use JSPs to mix html and servlets
* Introduction 
Servlets and JavaServer Pages (JSP) are technologies for building dynamic web applications. Servlets are Java classes that handle HTTP requests and responses, enabling server-side processing and business logic execution, while JSP allows for embedding Java code directly into HTML, simplifying the creation of interactive user interfaces. Together, they facilitate a clear separation of concerns, with servlets managing application flow and logic and JSP focusing on presentation, often following the Model-View-Controller (MVC) architecture to enhance maintainability and scalability in web development.
* Lab Work
** Write a servlet program illustrating the concept of HttpServlet class with proper illustration of the Deployment Descriptor.
*** Servlet
#+begin_src java
  import java.io.IOException;
  import java.io.PrintWriter;
  import javax.servlet.ServletException;
  import javax.servlet.http.*;

  public class HttpDemo extends HttpServlet {
      protected void processRequest(HttpServletRequest request, HttpServletResponse response)
          throws ServletException, IOException {
          response.setContentType("text/html;charset=UTF-8");
          try (PrintWriter out = response.getWriter()) {
              out.println("<!DOCTYPE html>");
              out.println("<html>");
              out.println("<head>");
              out.println("<title>Servlet question2</title>");
              out.println("</head>");
              out.println("<body>");
              out.println("Hello world");
              out.println("</body>");
              out.println("</html>");
          }
      }
      @Override
      protected void doGet(HttpServletRequest request, HttpServletResponse response)
              throws ServletException, IOException {
          processRequest(request, response);
      }
      @Override
      protected void doPost(HttpServletRequest request, HttpServletResponse response)
              throws ServletException, IOException {
          processRequest(request, response);
      }
      @Override
      public String getServletInfo() {
          return "Short description";
      }// </editor-fold>

  }
#+end_src
*** Descriptor
#+begin_src xml
  <?xml version="1.0" encoding="UTF-8"?>
  <web-app version="4.0" xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee           http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd">
    <servlet>
      <servlet-name>httpDemo</servlet-name>
      <servlet-class>HttpDemo</servlet-class>
    </servlet>
    <servlet-mapping>
      <servlet-name>httpDemo</servlet-name>
      <url-pattern>/demo</url-pattern>
    </servlet-mapping>
  </web-app>
#+end_src
** Write a sevlet program to illustrate form handling.
Design a html page consisting of fields like Name, Address, Email, Gender (Radio Button), district (Drop Down), vehicle type (checkbox) and a submit button. The servlet must insert the entered data into the database
*** Register.html
#+begin_src html
  <!DOCTYPE html>
  <html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
      <h1>Insert new student</h1>
      <form action="insertStudent" method="post">
        <label>
          First name: 
          <input type="text" name="fName" value="John"/>
        </label>
        <label>
          Last name: 
          <input type="text" name="lName" value="Doe"/>
        </label>
        <label>
          District:
          <select name="district">
            <option value="KTM">KTM</option>
            <option value="Pokhara">Pokhara</option>
            <option value="Birgunj">Birgunj</option>
          </select>
        </label>
        <div>
          Gender:
          <div>
            <label>
              <input type="radio" name="gender" value="male" checked />
              Male
            </label>
            <label>
              <input type="radio" name="gender" value="female" />
              Female
            </label>
            <label>
              <input type="radio" name="gender" value="other" />
              Other
            </label>
          </div>
        </div>
        <label>
          Vehicle type: 
          <label>
            <input type="checkbox" name="vehcile-bus" value="bus" checked />
            Bus:
          </label>
          <label>
            <input type="checkbox" name="vehcile-bike" value="bike" />
            Bike:
          </label>
          <label>
            <input type="checkbox" name="vehcile-car" value="car" />
            Car:
          </label>
        </label>
        <label>
          Email: <input type="email" name="email" />
        </label>
        <label>
          Password: <input type="password" name="password" />
        </label>
        <input type="submit" value="Submit" />
        <a href="signIn.html">Sign in instead</a>
      </form>
    </body>
  </html>
#+end_src
*** InsertStudent.java
#+begin_src java
  package database.student;

  import jakarta.servlet.RequestDispatcher;
  import jakarta.servlet.ServletException;
  import jakarta.servlet.annotation.*;
  import jakarta.servlet.http.*;
  import java.io.IOException;
  import java.io.PrintWriter;
  import java.sql.*;
  @WebServlet(name = "InsertStudent", urlPatterns = {"/InsertStudent"})
  public class InsertStudent extends HttpServlet {
      protected void processRequest(HttpServletRequest request, HttpServletResponse response)
          throws ServletException, IOException {
          response.setContentType("text/html;charset=UTF-8");
          try (PrintWriter out = response.getWriter()) {
              String fName = request.getParameter("fName");
              String lName = request.getParameter("lName");
              String district = request.getParameter("district");
              String gender = request.getParameter("gender");
              String[] vehicleInputNames = {"vehcile-bus", "vehcile-bike", "vehcile-car"};
              String vehicle = "";

              for (String v : vehicleInputNames) {
                  if (request.getParameter(v) != null) {
                      vehicle += request.getParameter(v) + ", ";
                      break;
                  }
              }

              String email="", password="";
              email = request.getParameter("email");
              password = request.getParameter("password");

              Class.forName("com.mysql.jdbc.Driver");
              Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/javadb", "root", "");
              String sql = "insert into student(first_name, last_name, gender, district, vehicle_type, email, password_plain_text) values"
                  + "(?, ?, ?, ?, ?, ?, ?)";
              PreparedStatement ps = conn.prepareStatement(sql);
              ps.setString(1, fName);
              ps.setString(2, lName);
              ps.setString(3, district);
              ps.setString(4, gender);
              ps.setString(5, vehicle);
              ps.setString(6, email);
              ps.setString(7, password);
              ps.execute();
              ps.close();
              conn.close();

              RequestDispatcher rd = request.getRequestDispatcher("signIn.html");
              rd.forward(request, response);
          } catch (Exception e) {
              System.err.println(e.getMessage());
          }
      }

      @Override
      protected void doGet(HttpServletRequest request, HttpServletResponse response)
          throws ServletException, IOException {
          processRequest(request, response);
      }
      @Override
      protected void doPost(HttpServletRequest request, HttpServletResponse response)
          throws ServletException, IOException {
          processRequest(request, response);
      }

      @Override
      public String getServletInfo() {
          return "Short description";
      }// </editor-fold>

  }
#+end_src
** Display the data inserted in question 3 in tabular format using a Servlet.
#+begin_src java
  package database.student;

  import java.io.IOException;
  import java.io.PrintWriter;
  import jakarta.servlet.*;
  import jakarta.servlet.annotation.WebServlet;
  import jakarta.servlet.http.*;
  import java.sql.*;
  import java.util.Arrays;

  @WebServlet(name = "ViewDetails", urlPatterns = {"/viewDetails"})
  public class ViewDetails extends HttpServlet {
      protected void processRequest(HttpServletRequest request, HttpServletResponse response)
          throws ServletException, IOException {
          response.setContentType("text/html;charset=UTF-8");
          try (PrintWriter out = response.getWriter()) {
              DriverManager.registerDriver(new com.mysql.jdbc.Driver());
              Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/javadb", "root", "");
              String sql = "select id, first_name, last_name, gender, district, vehicle_type, email from student";
              Statement stmt = conn.createStatement();
              ResultSet rs = stmt.executeQuery(sql);

              out.println("<!DOCTYPE html>");
              out.println("<html>");
              out.println("<head>");
              out.println("<title>Servlet ViewDetails</title>");			
              out.println("<style>tr:nth-child(even){ background: gray;}</style>");
              out.println("</head>");
              out.println("<body>");
              out.println("<h1>Student details: </h1>");

              out.println("<table border='2'>");
              out.println("<thead>");
              out.println("<th>id</th>");
              out.println("<th>First Name</th>");
              out.println("<th>Last Name</th>");
              out.println("<th>Gender</th>");
              out.println("<th>District</th>");
              out.println("<th>Vehicle types</th>");
              out.println("<th>Email</th>");
              out.println("<th></th>");
              out.println("</thead>");

              while(rs.next()) {
                  out.println("<tr>");
                  for(int i=1; i<8; i++) {
                      out.println("<td>"+rs.getString(i)+"</td>");
                  }
                  out.println("<td><a href='deleteStudent?id="+rs.getString("id")+"'>Delete</a></td>");
                  out.println("</tr>");
              }
              out.println("/<table>");
              out.println("</body>");
              out.println("</html>");

              stmt.close();
              conn.close();
          } catch(Exception e) {
              System.err.println(Arrays.toString(e.getStackTrace()));
              System.err.println(e.getMessage());
          }
      }

      @Override
      protected void doGet(HttpServletRequest request, HttpServletResponse response)
          throws ServletException, IOException {
          processRequest(request, response);
      }
      @Override
      protected void doPost(HttpServletRequest request, HttpServletResponse response)
          throws ServletException, IOException {
          processRequest(request, response);
      }

      @Override
      public String getServletInfo() {
          return "Short description";
      }// </editor-fold>
  }
#+end_src
** Write a program to read the value of principal, interest rate and time from user and display the simple interest value using JSP.
#+begin_src html
  <%@ page contentType="text/html;charset=UTF-8" language="java" %>
  <html>
    <body>
      <form method="post">
        <label for="principal">Principal Amount:</label><br>
        <input type="text" id="principal" name="principal" required><br><br>
      
        <label for="rate">Rate of Interest (%):</label><br>
        <input type="text" id="rate" name="rate" required><br><br>
      
        <label for="time">Time (years):</label><br>
        <input type="text" id="time" name="time" required><br><br>
      
        <input type="submit" value="Calculate Interest">
      </form>

      <%
        String principalStr = request.getParameter("principal");
        String rateStr = request.getParameter("rate");
        String timeStr = request.getParameter("time");

        double principal = Double.parseDouble(principalStr);
        double rate = Double.parseDouble(rateStr);
        double time = Double.parseDouble(timeStr);
        out.println((principal * rate * time) / 100);
        %>
    </body>
  </html>
#+end_src
** Write a program to read a String value from user and its reverse using JSP.
#+begin_src html
  <%@ page contentType="text/html;charset=UTF-8" language="java" %>
  <html>
  <body>
      <form method="post">
          <label for="inputString">Enter a String:</label><br>
          <input type="text" id="inputString" name="inputString" required><br><br>
          <input type="submit" value="Reverse String">
      </form>
      <%
          String inputString = request.getParameter("inputString");
          if (inputString != null) 
              out.println(new StringBuilder(inputString).reverse().toString());
      %>
  </body>
  </html>
#+end_src
* Conclusion
We implemented server-side code using servlets to handle business logic. By integrating JavaServer Pages (JSP), we effectively mixed HTML with Java code. 
